name: Bug Report
description: Report a bug or issue with Agents CLI
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out the information below to help us diagnose and fix the issue.

        **⚠️ Security Note**: If this is a security vulnerability, please don't file a public issue. Instead, follow our [Security Policy](../../SECURITY.md).

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is
      placeholder: Describe what happened and what you expected to happen
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Detailed steps to reproduce the issue
      placeholder: |
        1. Run `agents-cli run --config example.json`
        2. Enter input "Review this code"
        3. See error message...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened instead
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which component is affected?
      options:
        - CLI Interface
        - MCP Server
        - Configuration System
        - Security Framework
        - Tool Integration
        - Workflow Engine
        - OpenAI SDK Integration
        - Documentation
        - Other
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Information about your environment
      value: |
        - OS:
        - Node.js version:
        - Agents CLI version:
        - IDE:
        - OpenAI SDK version:
    validations:
      required: true

  - type: textarea
    id: config
    attributes:
      label: Configuration
      description: Your workflow configuration (remove any sensitive data like API keys)
      render: json
      placeholder: |
        {
          "agents": {
            "code_reviewer": {
              "name": "Code Reviewer",
              "instructions": "Review code for issues",
              "model": "gpt-4o"
            }
          }
        }

  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: Relevant logs or error messages (make sure to redact any API keys or sensitive information)
      render: text
      placeholder: Paste error logs here

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      options:
        - label: I have checked that this issue hasn't already been reported
          required: true
        - label: I have redacted any sensitive information (API keys, credentials, etc.)
          required: true
        - label: I have provided enough information to reproduce the issue
          required: true
        - label: I have tested with the latest version
          required: false