name: Feature Request
description: Suggest a new feature or enhancement for Agents CLI
title: "[Feature]: "
labels: ["enhancement", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please provide as much detail as possible to help us understand and evaluate your request.

        **📋 Note**: Check our [Phase Documentation](../../docs/tasks/) to see if your feature is already planned for future phases.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? What's the current limitation?
      placeholder: I'm frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the feature you'd like to see implemented
      placeholder: I'd like to be able to...
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which component would this feature affect?
      options:
        - CLI Interface
        - MCP Server
        - Configuration System
        - Security Framework
        - Tool Integration
        - Workflow Engine
        - OpenAI SDK Integration
        - Documentation
        - IDE Integration
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Nice to have
        - Would be helpful
        - Important for my use case
        - Critical for adoption
    validations:
      required: true

  - type: textarea
    id: use_case
    attributes:
      label: Use Case
      description: Describe a specific scenario where this feature would be useful
      placeholder: |
        When I'm working on a large codebase, I need to...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: What workarounds or alternative solutions have you considered?
      placeholder: I could work around this by...

  - type: textarea
    id: example
    attributes:
      label: Example Implementation
      description: If you have ideas about how this might work, share them here
      placeholder: |
        # CLI Usage
        agents-cli run --config my-workflow.json --new-feature

        # Configuration
        {
          "new_feature": {
            "option": "value"
          }
        }

  - type: dropdown
    id: breaking
    attributes:
      label: Breaking Change
      description: Would this require breaking changes to existing APIs?
      options:
        - No breaking changes needed
        - Minor breaking changes acceptable
        - Major breaking changes required
        - Not sure

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      options:
        - label: I have searched existing issues and feature requests
          required: true
        - label: I have checked the phase documentation for planned features
          required: true
        - label: I have provided a clear use case and problem statement
          required: true